---
editor_name_type:
  type: string
  form:
    required: true
    multiple: false
    type: select
    authority: HykuAddons::NameTypeService
editor_family_name:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - Personal
editor_given_name:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - Personal
editor_orcid:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - Personal
editor_institutional_relationship:
  type: string
  form:
    required: false
    multiple: false
    type: select
    authority: HykuAddons::InstitutionalRelationshipService
    display_for:
      - Personal
editor_organization_name:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - Organizational
editor_isni:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
      - Personal
      - Organizational

