attributes:
  title:
    type: string
    predicate: http://purl.org/dc/terms/title
    multiple: true
    index_keys:
      - title_tesim
      - title_sim
    form:
      required: true
      primary: true
      multiple: true
      type: text
      input: single_multi_value
  alt_title:
    type: string
    predicate: http://purl.org/dc/terms/alternative
    multiple: false
    index_keys:
      - alt_title_tesim
    form:
      required: false
      primary: true
      multiple: false
      type: text
  resource_type:
    predicate: http://purl.org/dc/terms/type
    multiple: true
    index_keys:
      - resource_type_tesim
      - resource_type_sim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::ResourceTypesService
      include_blank: true
      input: single_multi_value_select
  creator:
    predicate: http://purl.org/dc/elements/1.1/creator
    multiple: true
    index_keys:
      - creator_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: text
    subfields:
      creator_name_type:
        type: string
        form:
          required: true
          multiple: false
          type: select
          authority: HykuAddons::NameTypeService
      creator_family_name:
        type: string
        form:
          required: true
          multiple: false
          type: text
          display_for:
            - Personal
      creator_given_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_middle_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_suffix:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_institution:
        type: string
        form:
          required: false
          multiple: true
          type: text
          display_for:
            - Personal
      creator_role:
        type: string
        form:
          required: false
          multiple: true
          type: select
          authority: HykuAddons::RoleService
          include_blank: true
          display_for:
            - Personal
      creator_orcid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_institutional_email:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      creator_institutional_relationship:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::InstitutionalRelationshipService
          attributes:
            multiple: multiple
          display_for:
            - Personal
      creator_organization_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_ror:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_grid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_wikidata:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      creator_isni:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
            - Organizational
  alt_email:
    type: string
    predicate: http://schema.org/email
    multiple: true
    index_keys:
      - alt_email_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: text
  abstract:
    type: text
    predicate: http://purl.org/dc/terms/abstract
    multiple: false
    index_keys:
      - abstract_tesim
    form:
      required: true
      primary: true
      multiple: false
      type: textarea
  keyword:
    predicate: http://purl.org/dc/elements/1.1/relation
    multiple: true
    index_keys:
      - keyword_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: text
  subject:
    predicate: http://purl.org/dc/elements/1.1/subject
    multiple: true
    index_keys:
      - subject_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::SubjectService
  org_unit:
    type: string
    predicate: http://www.w3.org/ns/org#OrganizationalUnit
    multiple: true
    index_keys:
      - org_unit_tesim
      - org_unit_sim
    form:
      required: true
      primary: true
      multiple: true
      type: text
  audience:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/IntendedAudience
    multiple: true
    index_keys:
      - audience_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::AudienceService
  language:
    predicate: http://purl.org/dc/elements/1.1/language
    multiple: true
    index_keys:
      - language_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::LanguageService
  license:
    predicate: http://purl.org/dc/terms/rights
    multiple: true
    index_keys:
      - license_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: select
      authority: HykuAddons::LicenseService
  table_of_contents:
    type: string
    predicate: http://bibframe.org/vocab/tableOfContents
    multiple: false
    index_keys:
      - table_of_contents_tesim
    form:
      required: true
      primary: true
      multiple: false
      type: textarea
  publisher:
    predicate: http://purl.org/dc/elements/1.1/publisher
    multiple: true
    index_keys:
      - publisher_tesim
    form:
      required: true
      primary: true
      multiple: true
      type: text
  place_of_publication:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/Place
    multiple: true
    index_keys:
      - place_of_publication_tesim
      - place_of_publication_sim
    form:
      required: true
      primary: true
      multiple: true
      type: text
  date_published:
    type: string
    predicate: http://purl.org/dc/terms/available
    multiple: false
    index_keys:
      - date_published_tesim
    form:
      required: true
      primary: true
      multiple: false
      type: date
  doi:
    type: string
    predicate: http://purl.org/ontology/bibo/doi
    multiple: true
    index_keys:
      - doi_ssi
    form:
      required: false
      primary: true
      multiple: true
      type: text
  edition:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/edition
    multiple: false
    index_keys:
      - edition_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  pagination:
    type: string
    predicate: http://purl.org/ontology/bibo/numPages
    multiple: false
    index_keys:
      - pagination_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  official_link:
    type: string
    predicate: http://schema.org/url
    multiple: false
    index_keys:
      - official_link_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  adapted_from:
    type: string
    predicate: http://purl.org/dc/elements/1.1/source
    multiple: false
    index_keys:
      - adapted_from_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: textarea
  contributor:
    predicate: http://purl.org/dc/elements/1.1/contributor
    multiple: true
    index_keys:
      - contributor_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text
    subfields:
      contributor_name_type:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::NameTypeService
      contributor_family_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      contributor_given_name:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      contributor_orcid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
      contributor_institutional_relationship:
        type: string
        form:
          required: false
          multiple: false
          type: select
          authority: HykuAddons::ContributorInstitutionalRelationshipService
          attributes:
            multiple: multiple
          display_for:
            - Personal
      contributor_organization_name:
        type: string
        form:
          required: false
          multiple: true
          type: text
          display_for:
            - Organizational
      contributor_ror:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      contributor_grid:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      contributor_wikidata:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Organizational
      contributor_isni:
        type: string
        form:
          required: false
          multiple: false
          type: text
          display_for:
            - Personal
            - Organizational
      contributor_role:
        type: string
        form:
          required: false
          multiple: true
          type: select
          authority: HykuAddons::RoleService
          display_for:
            - Personal
            - Organizational
  related_material:
    type: string
    predicate: http://id.loc.gov/ontologies/bibframe/relatedTo
    multiple: false
    index_keys:
      - related_material_tesim
      - related_material_sim
    form:
      required: false
      primary: false
      multiple: false
      type: textarea
  longitude:
    type: string
    predicate: http://schema.org/longitude
    multiple: false
    index_keys:
      - longitude_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  latitude:
    type: string
    predicate: http://schema.org/latitude
    multiple: false
    index_keys:
      - latitude_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: text
  prerequisites:
    type: string
    predicate: http://creativecommons.org/ns#Requirement
    multiple: false
    index_keys:
      - prerequisites_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: textarea
  suggested_student_reviewers:
    type: string
    predicate: http://rdf.data-vocabulary.org/#reviewer
    multiple: false
    index_keys:
      - suggested_student_reviewers_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: textarea
  suggested_reviewers:
    type: string
    predicate: http://data-vocabulary.org/reviewer
    multiple: false
    index_keys:
      - suggested_reviewers_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: textarea
  add_info:
    type: string
    predicate: http://purl.org/ontology/bibo/Note
    multiple: false
    index_keys:
      - add_info_tesim
    form:
      required: false
      primary: false
      multiple: false
      type: textarea
  source:
    predicate: http://purl.org/dc/terms/source
    multiple: true
    index_keys:
      - source_tesim
    form:
      required: false
      primary: false
      multiple: true
      type: text