terms:
- id: BA
  term: BA
  active: true
- id: BA - Honors
  term: BA - Honors
  active: true
- id: BS
  term: BS
  active: true
- id: BS - Honors
  term: BS - Honors
  active: true
- id: DNP
  term: DNP - Nursing Practice
  active: true
- id: DPT
  term: DPT - Physical Therapy
  active: true
- id: EdD
  term: Ed.D - Executive Leadership
  active: true
- id: EdD
  term: Ed.D - Higher Education Leadership & Practice
  active: true
- id: MBA
  term: MBA
  active: true
- id: MAcc
  term: M.Acc. - Accounting
  active: true
- id: MEd-CurriculumInstruction
  term: M.Ed - Curriculum & Instruction
  active: true
- id: MEd-EarlyChildhoodEducation
  term: M.Ed - Early Childhood Education
  active: true
- id: M.Ed. - Education
  term: M.Ed. - Education
  active: true
- id: MEd-MiddleGradesMathScience
  term: M.Ed - Middle Grades Math & Science
  active: true
- id: MA-History
  term: MA - History
  active: true
- id: MAIA
  term: MAIA - International Affairs
  active: true
- id: MAT
  term: MAT - Teaching
  active: true
- id: MBA
  term: MBA - Business Administration
  active: true
- id: MPA
  term: MPA - Public Administration
  active: true
- id: MS
  term: MS
  active: true
- id: MS - Arts Administration
  term: MS - Arts Administration
  active: true
- id: MS - Information Systems
  term: MS - Information Systems
  active: true
- id: MS - Occupational Therapy
  term: MS - Occupational Therapy
  active: true
- id: MS - Physician Assistant
  term: MS - Physician Assistant
  active: true
- id: MSc-AthleticTraining
  term: MS - Athletic Training
  active: true
- id: MSc-Counseling
  term: MS - Counseling
  active: true
- id: MSc-CriminalJustice
  term: MS - Criminal Justice
  active: true
- id: MSc-HumanServicesDeliveryAdministration
  term: MS - Human Services Delivery & Administration
  active: true
- id: MSc-Kinesiology
  term: MS - Kinesiology
  active: true
- id: MSN-FamilyNursePractitioner
  term: MSN - Family Nurse Practitioner
  active: true
- id: M.S.T.
  term: M.S.T.
  active: true
- id: PhD-CriminalJustice
  term: Ph.D - Criminal Justice
  active: true
- id: PPDPT
  term: PPDPT - Physical Therapy
  active: true
