terms:
  - id: ARK
    term: ARK
  - id: arXiv
    term: arXiv
  - id: bibcode
    term: bibcode
  - id: DOI
    term: DOI
  - id: Handle
    term: Handle
  - id: IGSN
    term: IGSN
  - id: ISBN
    term: ISBN
  - id: ISSN
    term: ISSN
  - id: PMID
    term: PMID
  - id: PURL
    term: PURL
  - id: URL
    term: URL
  - id: URN
    term: URN
