terms:
  - id: Dataset
    term: Dataset
  - id: Numerical dataset
    term: Numerical dataset
  - id: Geographical dataset
    term: Geographical dataset
  - id: Software
    term: Software
  - id: Database
    term: Database

