terms:
  - id: Quantitative Data
    term: Quantitative Data
  - id: Qualitative Data
    term: Qualitative Data
  - id: Geospatial Data
    term: Geospatial Data
  - id: Data
    term: Data
  - id: Database
    term: Database
  - id: Other
    term: Other
