terms:
  - id: Blog post
    term: Blog post
  - id: Cartographic material
    term: Cartographic material
  - id: Interactive resource
    term: Interactive resource
  - id: Learning object
    term: Learning object
  - id: Musical notation
    term: Musical notation
  - id: Patent
    term: Patent
  - id: Website
    term: Website
  - id: Workflow
    term: Workflow
  - id: Other
    term: Other

