terms:
  - id: Published article
    term: Published article
  - id: Pre-print / Post-print
    term: Pre-print / Post-print
  - id: White paper
    term: White paper
  - id: Review
    term: Review
  - id: Creative work
    term: Creative work
  - id: Editorial/Commentary
    term: Editorial/Commentary
  - id: Essay
    term: Essay
  - id: Other
    term: Other
