terms:
 - id: Accounting & Law
   term: Accounting & Law
   active: true
 - id: Appalachian Studies
   term: Appalachian Studies
   active: true  
 - id: Biology
   term: Biology
   active: true
 - id: Business
   term: Business
   active: true
 - id: Chemistry & Biochemistry
   term: Chemistry & Biochemistry
   active: true
 - id: Communication, Media, & Journalism
   term: Communication, Media, & Journalism
   active: true
 - id: Computer Science & Information Systems
   term: Computer Science & Information Systems
   active: true
 - id: Counseling
   term: Counseling
   active: true
 - id: Criminal Justice
   term: Criminal Justice
   active: true
 - id: Economics & Finance
   term: Economics & Finance
   active: true
 - id: Education
   term: Education
   active: true
 - id: Elementary & Special Education
   term: Elementary & Special Education
   active: true
 - id: English
   term: English
   active: true
 - id: Environmental Spatial Analysis
   term: Environmental Spatial Analysis
   active: true
 - id: History, Anthropology, & Philosophy
   term: History, Anthropology, & Philosophy
   active: true
 - id: Interdisciplinary Healthcare
   term: Interdisciplinary Healthcare
   active: true
 - id: Interdisciplinary Studies
   term: Interdisciplinary Studies
   active: true
 - id: Interdisciplinary Studies/University
   term: Interdisciplinary Studies/University
   active: true
 - id: Kinesiology
   term: Kinesiology
   active: true
 - id: Library Science
   term: Library Science
   active: true
 - id: Management & Marketing
   term: Management & Marketing
   active: true
 - id: Mathematics
   term: Mathematics
   active: true
 - id: Middle Grades, Secondary, & Science Education
   term: Middle Grades, Secondary, & Science Education
   active: true
 - id: Military Science
   term: Military Science
   active: true
 - id: Modern & Classical Languages
   term: Modern & Classical Languages
   active: true
 - id: Music
   term: Music
   active: true
 - id: Nursing
   term: Nursing
   active: true
 - id: Physical Therapy
   term: Physical Therapy
   active: true
 - id: Physics & Astronomy
   term: Physics & Astronomy
   active: true
 - id: Political Science & International Affairs
   term: Political Science & International Affairs
   active: true
 - id: Psychological Science
   term: Psychological Science
   active: true
 - id: Sociology & Human Services
   term: Sociology & Human Services
   active: true
 - id: Theatre
   term: Theatre
   active: true
 - id: Visual Arts
   term: Visual Arts
   active: true
 - id: Other
   term: Other
   active: true